# Generated by Django 5.2.6 on 2026-03-07 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software', models.CharField(help_text='Ej: Office, AutoCAD', max_length=200, verbose_name='Nombre del software')),
                ('version', models.CharField(help_text='Ej: 2021, 365', max_length=50, verbose_name='Versión')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('tipo_licencia', models.CharField(choices=[('perpetua', 'Perpetua'), ('suscripcion', 'Suscripción'), ('oem', 'OEM'), ('volumen', 'Volumen'), ('libre', 'Libre / Open Source')], max_length=30, verbose_name='Tipo de licencia')),
                ('licencias_totales', models.IntegerField(default=0, verbose_name='Licencias totales')),
                ('fecha_expiracion', models.DateField(blank=True, null=True, verbose_name='Fecha de expiración')),
                ('costo_anual_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Costo anual/total')),
            ],
            options={
                'verbose_name': 'Producto de Software',
                'verbose_name_plural': 'Productos de Software',
                'db_table': 'productos_software',
                'ordering': ['software', 'version'],
                'indexes': [models.Index(fields=['software'], name='idx_producto_sw_nombre'), models.Index(fields=['tipo_licencia'], name='idx_producto_sw_tipo')],
                'constraints': [models.UniqueConstraint(fields=('software', 'version'), name='uq_software_version')],
            },
        ),
        migrations.CreateModel(
            name='SoftwareInstalado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_licencia_usado', models.CharField(blank=True, default='', max_length=255, verbose_name='Número de licencia usado')),
                ('fecha_instalacion', models.DateField(verbose_name='Fecha de instalación')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_instalado', to='equipos.equipo', verbose_name='Equipo')),
                ('producto_software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalaciones', to='software.productosoftware', verbose_name='Producto de software')),
            ],
            options={
                'verbose_name': 'Software Instalado',
                'verbose_name_plural': 'Software Instalados',
                'db_table': 'software_instalado',
                'constraints': [models.UniqueConstraint(fields=('equipo', 'producto_software'), name='uq_equipo_software')],
            },
        ),
    ]
