# Generated by Django 4.2.29 on 2026-06-11 08:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoSoftware',
            fields=[
                ('id_producto_software', models.AutoField(primary_key=True, serialize=False)),
                ('software', models.CharField(max_length=255, verbose_name='Software')),
                ('version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Versión')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('tipo_licencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de licencia')),
                ('licencias_totales', models.IntegerField(default=0, verbose_name='Licencias totales')),
                ('fecha_expiracion', models.DateField(blank=True, null=True, verbose_name='Fecha de expiración')),
                ('costo_anual_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo anual total')),
            ],
            options={
                'verbose_name': 'Producto de Software',
                'verbose_name_plural': 'Productos de Software',
                'db_table': 'productos_software',
            },
        ),
        migrations.CreateModel(
            name='SoftwareInstalado',
            fields=[
                ('id_instalacion', models.AutoField(primary_key=True, serialize=False)),
                ('numero_licencia_usado', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de licencia usado')),
                ('fecha_instalacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de instalación')),
                ('equipo', models.ForeignKey(db_column='id_equipo_fk', on_delete=django.db.models.deletion.CASCADE, related_name='software_instalado', to='equipos.equipo', verbose_name='Equipo')),
                ('producto_software', models.ForeignKey(db_column='id_producto_software_fk', on_delete=django.db.models.deletion.CASCADE, related_name='instalaciones', to='software.productosoftware', verbose_name='Producto de software')),
            ],
            options={
                'verbose_name': 'Software Instalado',
                'verbose_name_plural': 'Software Instalado',
                'db_table': 'software_instalado',
            },
        ),
        migrations.AddConstraint(
            model_name='productosoftware',
            constraint=models.UniqueConstraint(fields=('software', 'version'), name='uq_software_version'),
        ),
        migrations.AddConstraint(
            model_name='softwareinstalado',
            constraint=models.UniqueConstraint(fields=('equipo', 'producto_software'), name='uq_equipo_software'),
        ),
    ]
