# Generated by Django 4.2.30 on 2026-08-15 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_productosoftware_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='softwareinstalado',
            options={'ordering': ['-fecha_instalacion', 'id'], 'verbose_name': 'Software Instalado', 'verbose_name_plural': 'Software Instalados'},
        ),
    ]
