# Generated by Django 5.2.6 on 2026-03-07 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del evento')),
                ('descripcion', models.TextField(help_text='Ej: Se asignó a laboratorio LAB-203', verbose_name='Descripción')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='equipos.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historiales',
                'db_table': 'historial',
                'ordering': ['-fecha'],
            },
        ),
    ]
