# Generated by Django 4.2.30 on 2026-08-02 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del evento')),
                ('tipo_evento', models.CharField(help_text='Formato modulo.accion — ej. equipo.cambio_estado', max_length=100, verbose_name='Tipo de evento')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID del objeto')),
                ('descripcion', models.TextField(help_text='Texto legible para mostrar en interfaz.', verbose_name='Descripción')),
                ('datos_extra', models.JSONField(blank=True, help_text='Estado anterior, nuevo valor, IDs relacionados, etc.', null=True, verbose_name='Datos adicionales')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de objeto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_generados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Evento de auditoría',
                'verbose_name_plural': 'Historial de auditoría',
                'db_table': 'historial',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'fecha'], name='idx_historial_objeto_fecha'), models.Index(fields=['fecha'], name='idx_historial_fecha'), models.Index(fields=['usuario'], name='idx_historial_usuario'), models.Index(fields=['tipo_evento'], name='idx_historial_tipo')],
            },
        ),
    ]
