# Generated by Django 5.2.6 on 2026-03-07 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historial', '0001_initial'),
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='mantenimiento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial', to='mantenimiento.mantenimiento', verbose_name='Mantenimiento asociado'),
        ),
        migrations.AddIndex(
            model_name='historial',
            index=models.Index(fields=['fecha'], name='idx_historial_fecha'),
        ),
        migrations.AddIndex(
            model_name='historial',
            index=models.Index(fields=['equipo'], name='idx_historial_equipo'),
        ),
    ]
