# Generated by Django 5.2.6 on 2026-03-07 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
        ('espacios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de generación')),
                ('descripcion', models.TextField(verbose_name='Descripción de la incidencia')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias', to='equipos.equipo', verbose_name='Equipo afectado')),
                ('espacio', models.ForeignKey(help_text='Espacio donde ocurrió la incidencia (obligatorio)', on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='espacios.espacio', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'db_table': 'incidencias',
                'ordering': ['-fecha_generado'],
            },
        ),
    ]
