# Generated by Django 4.2.29 on 2026-06-11 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantenimiento', '0001_initial'),
        ('equipos', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('espacios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_generado', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('resuelta', 'Resuelta'), ('cerrada', 'Cerrada')], default='pendiente', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20)),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('solucion', models.TextField(blank=True, null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('equipo', models.ForeignKey(blank=True, db_column='id_equipo_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias', to='equipos.equipo')),
                ('espacio', models.ForeignKey(blank=True, db_column='id_espacio_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias', to='espacios.espacio')),
                ('mantenimiento', models.ForeignKey(blank=True, db_column='id_mantenimiento_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias', to='mantenimiento.mantenimiento')),
                ('tecnico_asignado', models.ForeignKey(blank=True, db_column='id_tecnico_asignado_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_asignadas', to='usuarios.perfiltecnico')),
                ('usuario', models.ForeignKey(blank=True, db_column='id_usuario_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'incidencias',
                'indexes': [models.Index(fields=['fecha_generado'], name='idx_incidencia_fecha'), models.Index(fields=['usuario'], name='idx_incidencia_usuario'), models.Index(fields=['estado'], name='idx_incidencia_estado')],
            },
        ),
    ]
