# Generated by Django 5.2.6 on 2026-03-07 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidencias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que reporta'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['fecha_generado'], name='idx_incidencia_fecha'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['usuario'], name='idx_incidencia_usuario'),
        ),
    ]
