# Generated by Django 4.2.30 on 2026-08-03 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidencias', '0003_incidencia_created_at_incidencia_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='incidencia',
            name='idx_incidencia_usuario',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='usuario',
        ),
        migrations.AddField(
            model_name='incidencia',
            name='docente',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'docente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_reportadas', to=settings.AUTH_USER_MODEL, verbose_name='Docente que reporta'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='tecnico',
            field=models.ForeignKey(default=1, limit_choices_to={'rol': 'tecnico'}, on_delete=django.db.models.deletion.CASCADE, related_name='incidencias_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Técnico que registra'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['tecnico'], name='idx_incidencia_tecnico'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['docente'], name='idx_incidencia_docente'),
        ),
    ]
