# Generated by Django 4.2.30 on 2026-08-17 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_componente_created_at_componente_created_by_and_more'),
        ('espacios', '0004_espacio_activo'),
        ('incidencias', '0004_remove_incidencia_idx_incidencia_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidencia',
            options={'ordering': ['-created_at'], 'verbose_name': 'Incidencia', 'verbose_name_plural': 'Incidencias'},
        ),
        migrations.RemoveIndex(
            model_name='incidencia',
            name='idx_incidencia_fecha',
        ),
        migrations.RemoveIndex(
            model_name='incidencia',
            name='idx_incidencia_tecnico',
        ),
        migrations.RemoveIndex(
            model_name='incidencia',
            name='idx_incidencia_docente',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='fecha_generado',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='tecnico',
        ),
        migrations.AddField(
            model_name='incidencia',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('resuelto', 'Resuelto')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='fecha_resolucion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de resolución'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='tipo_incidencia',
            field=models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software')], default='hardware', max_length=20, verbose_name='Tipo de incidencia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='equipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='equipos.equipo', verbose_name='Equipo afectado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='espacio',
            field=models.ForeignKey(help_text='Espacio donde ocurrió la incidencia', on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='espacios.espacio', verbose_name='Ubicación'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['estado'], name='idx_incidencia_estado'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['tipo_incidencia'], name='idx_incidencia_tipo'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['espacio'], name='idx_incidencia_espacio'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['equipo'], name='idx_incidencia_equipo'),
        ),
    ]
