# Generated by Django 4.2.29 on 2026-06-11 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espacios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de serie')),
                ('numero_mac', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección MAC')),
                ('tipo_equipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de equipo')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('modo_adquisicion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modo de adquisición')),
                ('fecha_adquisicion', models.DateField(blank=True, null=True, verbose_name='Fecha de adquisición')),
                ('fecha_renovacion', models.DateField(blank=True, null=True, verbose_name='Fecha de renovación')),
                ('estado', models.CharField(choices=[('no usado', 'No usado'), ('en uso', 'En uso'), ('en mantenimiento', 'En mantenimiento'), ('dañado', 'Dañado')], default='no usado', max_length=20, verbose_name='Estado')),
                ('espacio', models.ForeignKey(blank=True, db_column='id_espacio_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='espacios.espacio', verbose_name='Espacio')),
                ('responsable', models.ForeignKey(blank=True, db_column='id_responsable_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_a_cargo', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'equipos',
            },
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id_componente', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo')),
                ('modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de serie')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('equipo', models.ForeignKey(db_column='id_equipo_fk', on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='equipos.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
                'db_table': 'componentes',
            },
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['codigo'], name='idx_equipo_codigo'),
        ),
    ]
