# Generated by Django 5.2.6 on 2026-03-07 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espacios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Identificador interno del equipo', max_length=50, unique=True, verbose_name='Código interno')),
                ('numero_serie', models.CharField(help_text='Número de serie del fabricante', max_length=100, unique=True, verbose_name='Número de serie')),
                ('numero_mac', models.CharField(blank=True, default='', help_text='Ej: MAC:10001:10F', max_length=50, verbose_name='Dirección MAC')),
                ('tipo_equipo', models.CharField(choices=[('desktop', 'Desktop'), ('laptop', 'Laptop'), ('servidor', 'Servidor'), ('impresora', 'Impresora'), ('proyector', 'Proyector'), ('monitor', 'Monitor'), ('otro', 'Otro')], max_length=30, verbose_name='Tipo de equipo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('modo_adquisicion', models.CharField(choices=[('comprado', 'Comprado'), ('arrendado', 'Arrendado'), ('donado', 'Donado')], max_length=20, verbose_name='Modo de adquisición')),
                ('fecha_adquisicion', models.DateField(verbose_name='Fecha de adquisición')),
                ('fecha_renovacion', models.DateField(blank=True, help_text='Solo si aplica (equipos arrendados)', null=True, verbose_name='Fecha de renovación')),
                ('estado', models.CharField(choices=[('en_uso', 'En uso'), ('en_mantenimiento', 'En mantenimiento'), ('dañado', 'Dañado'), ('de_baja', 'De baja')], default='en_uso', max_length=20, verbose_name='Estado')),
                ('responsable_usuario', models.CharField(blank=True, default='', max_length=255, verbose_name='Usuario asignado/responsable')),
                ('espacio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='espacios.espacio', verbose_name='Espacio asignado')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'equipos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cpu', 'CPU'), ('ram', 'RAM'), ('ssd', 'SSD'), ('hdd', 'HDD'), ('gpu', 'GPU'), ('motherboard', 'Motherboard'), ('fuente', 'Fuente de Poder'), ('nic', 'Tarjeta de Red'), ('otro', 'Otro')], help_text='Ej: CPU, RAM, SSD', max_length=50, verbose_name='Tipo de componente')),
                ('modelo', models.CharField(help_text='Ej: Fury, Ryzen 5 5600X', max_length=100, verbose_name='Modelo')),
                ('descripcion', models.TextField(blank=True, default='', help_text='Ej: 16GB DDR4 3200MHz', verbose_name='Descripción/Detalle')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='equipos.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
                'db_table': 'componentes',
            },
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['codigo'], name='idx_equipo_codigo'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['numero_serie'], name='idx_equipo_serie'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['estado'], name='idx_equipo_estado'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['tipo_equipo'], name='idx_equipo_tipo'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['numero_mac'], name='idx_equipo_mac'),
        ),
    ]
