from .roles import (
    ROL_SUPERADMIN,
    ROL_ADMIN,
    ROL_RESPONSABLE,
    ROL_TECNICO,
    ROL_DOCENTE,
    ROL_USUARIO,
    ROLES,
    MODULOS_SISTEMA,
    ACCIONES_SISTEMA,
    ROL_PERMISOS_BASE,
)

__all__ = [
    'ROL_SUPERADMIN',
    'ROL_ADMIN',
    'ROL_RESPONSABLE',
    'ROL_TECNICO',
    'ROL_DOCENTE',
    'ROL_USUARIO',
    'ROLES',
    'MODULOS_SISTEMA',
    'ACCIONES_SISTEMA',
    'ROL_PERMISOS_BASE',
]

