# Generated by Django 4.2.29 on 2026-06-11 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('equipos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('tipo_mantenimiento', models.CharField(blank=True, choices=[('Preventivo', 'Preventivo'), ('Correctivo', 'Correctivo')], max_length=50, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('resuelto', 'Resuelto')], default='pendiente', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('observaciones_cierre', models.TextField(blank=True, null=True)),
                ('equipo', models.ForeignKey(db_column='id_equipo_fk', on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='equipos.equipo')),
                ('usuario_cierre', models.ForeignKey(blank=True, db_column='id_usuario_cierre_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_cerrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='TecnicoMantenimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mantenimiento', models.ForeignKey(db_column='id_mantenimiento_fk', on_delete=django.db.models.deletion.CASCADE, related_name='tecnicos_asignados', to='mantenimiento.mantenimiento')),
                ('tecnico', models.ForeignKey(db_column='id_tecnico_fk', on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos_asignados', to='usuarios.perfiltecnico')),
            ],
            options={
                'db_table': 'tecnico_mantenimiento',
            },
        ),
        migrations.AddConstraint(
            model_name='tecnicomantenimiento',
            constraint=models.UniqueConstraint(fields=('mantenimiento', 'tecnico'), name='uq_mantenimiento_tecnico'),
        ),
        migrations.AddIndex(
            model_name='mantenimiento',
            index=models.Index(fields=['estado'], name='idx_mant_estado'),
        ),
        migrations.AddIndex(
            model_name='mantenimiento',
            index=models.Index(fields=['tipo_mantenimiento'], name='idx_mant_tipo'),
        ),
        migrations.AddIndex(
            model_name='mantenimiento',
            index=models.Index(fields=['fecha_inicio'], name='idx_mant_fecha'),
        ),
    ]
