# Generated by Django 5.2.6 on 2026-03-07 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del ticket')),
                ('tipo_mantenimiento', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], max_length=20, verbose_name='Tipo de mantenimiento')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('resuelto', 'Resuelto'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('descripcion', models.TextField(verbose_name='Descripción del problema')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='equipos.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'db_table': 'mantenimiento',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='TecnicoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnicos_asignados', to='mantenimiento.mantenimiento', verbose_name='Mantenimiento')),
            ],
            options={
                'verbose_name': 'Asignación Técnico - Mantenimiento',
                'verbose_name_plural': 'Asignaciones Técnico - Mantenimiento',
                'db_table': 'tecnico_mantenimiento',
            },
        ),
    ]
