# Generated by Django 5.2.6 on 2026-03-07 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantenimiento', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnicomantenimiento',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos_asignados', to='usuarios.perfiltecnico', verbose_name='Técnico'),
        ),
        migrations.AddIndex(
            model_name='mantenimiento',
            index=models.Index(fields=['estado'], name='idx_mant_estado'),
        ),
        migrations.AddIndex(
            model_name='mantenimiento',
            index=models.Index(fields=['tipo_mantenimiento'], name='idx_mant_tipo'),
        ),
        migrations.AddIndex(
            model_name='mantenimiento',
            index=models.Index(fields=['fecha'], name='idx_mant_fecha'),
        ),
        migrations.AddConstraint(
            model_name='tecnicomantenimiento',
            constraint=models.UniqueConstraint(fields=('mantenimiento', 'tecnico'), name='uq_mantenimiento_tecnico'),
        ),
    ]
