# Generated by Django 4.2.29 on 2026-06-11 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pabellon',
            fields=[
                ('id_pabellon', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('total_pisos', models.IntegerField(default=1, verbose_name='Total de pisos')),
            ],
            options={
                'verbose_name': 'Pabellón',
                'verbose_name_plural': 'Pabellones',
                'db_table': 'pabellones',
            },
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id_espacio', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_espacio', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('piso', models.CharField(blank=True, max_length=20, null=True, verbose_name='Piso')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo')),
                ('capacidad', models.IntegerField(blank=True, null=True, verbose_name='Capacidad')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('pabellon', models.ForeignKey(blank=True, db_column='id_pabellon_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='espacios', to='espacios.pabellon', verbose_name='Pabellón')),
            ],
            options={
                'verbose_name': 'Espacio',
                'verbose_name_plural': 'Espacios',
                'db_table': 'espacios',
                'indexes': [models.Index(fields=['pabellon'], name='idx_espacio_pabellon')],
            },
        ),
    ]
