# Generated by Django 5.2.6 on 2026-03-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_espacio', models.CharField(help_text='Ej: LAB-203', max_length=50, unique=True, verbose_name='Código del espacio')),
                ('tipo', models.CharField(choices=[('laboratorio', 'Laboratorio'), ('oficina', 'Oficina'), ('aula', 'Aula'), ('sala_computo', 'Sala de Cómputo'), ('otro', 'Otro')], max_length=50, verbose_name='Tipo de espacio')),
                ('pabellon', models.CharField(help_text='Ej: Pabellón 1', max_length=100, verbose_name='Pabellón')),
                ('piso', models.CharField(max_length=20, verbose_name='Piso')),
            ],
            options={
                'verbose_name': 'Espacio',
                'verbose_name_plural': 'Espacios',
                'db_table': 'espacios',
                'ordering': ['codigo_espacio'],
                'indexes': [models.Index(fields=['codigo_espacio'], name='idx_espacio_codigo'), models.Index(fields=['tipo'], name='idx_espacio_tipo'), models.Index(fields=['pabellon'], name='idx_espacio_pabellon')],
            },
        ),
    ]
