# Generated by Django 4.2.29 and extended for data migration

import django.db.models.deletion
from django.db import migrations, models


def populate_scope_fields_from_espacio(apps, schema_editor):
    """
    Puebla local, edificio y piso para todas las asignaciones existentes
    basándose en el espacio individual actualmente asociado.
    """
    EspacioUsuario = apps.get_model('espacios', 'EspacioUsuario')
    Espacio = apps.get_model('espacios', 'Espacio')

    for asig in EspacioUsuario.objects.filter(espacio__isnull=False):
        try:
            espacio = Espacio.objects.select_related('edificio__local').get(id=asig.espacio_id)
        except Espacio.DoesNotExist:
            continue

        updated = False
        if asig.ambito != 'espacio':
            asig.ambito = 'espacio'
            updated = True

        if espacio.piso and not asig.piso:
            asig.piso = espacio.piso
            updated = True

        if espacio.edificio_id and not asig.edificio_id:
            asig.edificio_id = espacio.edificio_id
            updated = True

        if espacio.edificio_id and espacio.edificio and espacio.edificio.local_id and not asig.local_id:
            asig.local_id = espacio.edificio.local_id
            updated = True

        if updated:
            asig.save(update_fields=['ambito', 'piso', 'edificio', 'local'])


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0009_local_tipo'),
    ]

    operations = [
        # 1. Modificar campo 'espacio' para permitir nulos en asignaciones de Sede, Edificio y Piso
        migrations.AlterField(
            model_name='espaciousuario',
            name='espacio',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='asignaciones_usuario',
                to='espacios.espacio',
                verbose_name='Espacio individual',
            ),
        ),

        # 2. Agregar campo 'ambito' con valor por defecto 'espacio'
        migrations.AddField(
            model_name='espaciousuario',
            name='ambito',
            field=models.CharField(
                choices=[
                    ('sede', 'Sede'),
                    ('edificio', 'Pabellón/Edificio'),
                    ('piso', 'Piso'),
                    ('espacio', 'Espacio individual'),
                ],
                db_index=True,
                default='espacio',
                max_length=20,
                verbose_name='Nivel de ámbito territorial',
            ),
        ),

        # 3. Agregar campo 'local'
        migrations.AddField(
            model_name='espaciousuario',
            name='local',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='asignaciones_sede',
                to='espacios.local',
                verbose_name='Local / Sede',
            ),
        ),

        # 4. Agregar campo 'edificio'
        migrations.AddField(
            model_name='espaciousuario',
            name='edificio',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='asignaciones_edificio',
                to='espacios.edificio',
                verbose_name='Edificio / Pabellón',
            ),
        ),

        # 5. Agregar campo 'piso'
        migrations.AddField(
            model_name='espaciousuario',
            name='piso',
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name='Piso',
            ),
        ),

        # 6. Ejecutar Data Migration para poblar datos derivados de los 18 registros existentes
        migrations.RunPython(
            populate_scope_fields_from_espacio,
            reverse_code=migrations.RunPython.noop,
        ),

        # 7. Retirar la restricción de unicidad anterior (que no consideraba ámbitos ni nulos)
        migrations.RemoveConstraint(
            model_name='espaciousuario',
            name='uniq_espacio_usuario',
        ),

        # 8. Agregar las 4 restricciones de unicidad activas condicionales
        migrations.AddConstraint(
            model_name='espaciousuario',
            constraint=models.UniqueConstraint(
                condition=models.Q(('activo', True), ('ambito', 'sede'), ('is_deleted', False)),
                fields=('local', 'usuario'),
                name='uniq_asig_sede_activa',
            ),
        ),
        migrations.AddConstraint(
            model_name='espaciousuario',
            constraint=models.UniqueConstraint(
                condition=models.Q(('activo', True), ('ambito', 'edificio'), ('is_deleted', False)),
                fields=('edificio', 'usuario'),
                name='uniq_asig_edif_activa',
            ),
        ),
        migrations.AddConstraint(
            model_name='espaciousuario',
            constraint=models.UniqueConstraint(
                condition=models.Q(('activo', True), ('ambito', 'piso'), ('is_deleted', False)),
                fields=('edificio', 'piso', 'usuario'),
                name='uniq_asig_piso_activa',
            ),
        ),
        migrations.AddConstraint(
            model_name='espaciousuario',
            constraint=models.UniqueConstraint(
                condition=models.Q(('activo', True), ('ambito', 'espacio'), ('is_deleted', False)),
                fields=('espacio', 'usuario'),
                name='uniq_asig_espacio_activa',
            ),
        ),

        # 9. Agregar índices de optimización para filtros por ámbito y sedes
        migrations.AddIndex(
            model_name='espaciousuario',
            index=models.Index(fields=['ambito', 'activo'], name='idx_asig_amb_activa'),
        ),
        migrations.AddIndex(
            model_name='espaciousuario',
            index=models.Index(fields=['local', 'activo'], name='idx_asig_loc_activa'),
        ),
        migrations.AddIndex(
            model_name='espaciousuario',
            index=models.Index(fields=['edificio', 'activo'], name='idx_asig_edif_activa'),
        ),
        migrations.AddIndex(
            model_name='espaciousuario',
            index=models.Index(fields=['edificio', 'piso', 'activo'], name='idx_asig_edif_piso_act'),
        ),
    ]
