# Generated by Django 4.2.29 on 2026-06-11 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('correo', models.EmailField(max_length=100, unique=True, verbose_name='Correo electrónico')),
                ('password', models.CharField(db_column='contrasenia_hash', max_length=255, verbose_name='Hash de contrasena')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('tecnico', 'Tecnico'), ('usuario', 'Usuario')], default='usuario', max_length=20, verbose_name='Rol')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='PerfilTecnico',
            fields=[
                ('id_tecnico', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(default='', help_text='Ej: Cedeco, Soporte', max_length=100, verbose_name='Área')),
                ('usuario', models.OneToOneField(db_column='id_usuario_fk', on_delete=django.db.models.deletion.CASCADE, related_name='perfil_tecnico', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil Técnico',
                'verbose_name_plural': 'Perfiles Técnicos',
                'db_table': 'perfil_tecnico',
            },
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['correo'], name='idx_usuario_correo'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rol'], name='idx_usuario_rol'),
        ),
    ]
