# Generated by Django 4.2.29 on 2026-09-18 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0009_local_tipo'),
        ('usuarios', '0003_usuario_apellido_y_rol_docente'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado (Soft Delete)')),
                ('modulo', models.CharField(choices=[('espacios', 'Espacios'), ('equipos', 'Equipos'), ('mantenimiento', 'Mantenimiento'), ('incidencias', 'Incidencias'), ('software', 'Software'), ('usuarios', 'Usuarios'), ('auditoria', 'Auditoría')], max_length=50, verbose_name='Módulo')),
                ('accion', models.CharField(choices=[('ver', 'Ver'), ('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar')], max_length=20, verbose_name='Acción')),
                ('permitido', models.BooleanField(default=True, verbose_name='Permitido')),
            ],
            options={
                'verbose_name': 'Permiso Personalizado',
                'verbose_name_plural': 'Permisos Personalizados',
                'db_table': 'permisos_personalizados',
                'ordering': ['modulo', 'accion'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado (Soft Delete)')),
                ('es_sede_principal', models.BooleanField(default=False, verbose_name='¿Es sede principal?')),
                ('activo', models.BooleanField(default=True, verbose_name='Asignación activa')),
            ],
            options={
                'verbose_name': 'Asignación de Sede',
                'verbose_name_plural': 'Asignaciones de Sedes',
                'db_table': 'usuario_sedes',
                'ordering': ['-es_sede_principal', 'local__nombre'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor directo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'Superadministrador'), ('admin', 'Administrador'), ('responsable', 'Responsable de Sede / Área'), ('tecnico', 'Técnico'), ('docente', 'Docente'), ('usuario', 'Usuario')], default='usuario', max_length=20, verbose_name='Rol'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['supervisor'], name='idx_usuario_supervisor'),
        ),
        migrations.AddField(
            model_name='usuariosede',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='usuariosede',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_sedes', to='espacios.local', verbose_name='Local / Sede'),
        ),
        migrations.AddField(
            model_name='usuariosede',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='usuariosede',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_sedes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='permisopersonalizado',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='permisopersonalizado',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='permisopersonalizado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_personalizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sedes',
            field=models.ManyToManyField(blank=True, related_name='usuarios', through='usuarios.UsuarioSede', to='espacios.local', verbose_name='Sedes asignadas'),
        ),
        migrations.AlterUniqueTogether(
            name='usuariosede',
            unique_together={('usuario', 'local')},
        ),
        migrations.AlterUniqueTogether(
            name='permisopersonalizado',
            unique_together={('usuario', 'modulo', 'accion')},
        ),
    ]
